### ISSUE TITLE
Shift+arrow left/right MAC = ?

### ISSUE THREAD

**Issue by ImDino** [keycastr/keycastr#138] opened 2019-03-28 04:35 UTC
I found what would supposedly be a fix but I can't find those lines in any file, and I can't find "KCKeystrokeTansformer.m".

https://github.com/keycastr/keycastr/issues/106#issuecomment-397196699

I use a macbook pro, wireless apple keyboard.

Please help!

**Comment by Mark2Mark** [comment] 2019-05-20 16:33
+1

**Comment by bofeiw** [comment] 2019-08-18 10:42
+1

**Comment by akitchen** [comment] 2019-10-31 20:39
Combinations of Shift key with arrows, enter/return, esc, and delete key are all problematic.

I'm happy to review a PR if it fixes all of these, but I'm also thinking about a fix for the next version.

asdasdasd
asdasdasd

**Comment by akitchen** [comment] 2020-12-11 22:22
Duplicate of #106 and fixed on master

**Closed by akitchen** 2020-12-11 22:22 UTC
