### ISSUE TITLE
Display Double keystroke when I typing

### ISSUE THREAD

**Issue by minhden11hcm** [keycastr/keycastr#273] opened 2023-06-11 19:32 UTC
When i typing the keystroke display twice, Any one help me resolve it thanks

**Comment by akitchen** [comment] 2023-06-23 23:09
KeyCastr displays whatever events are emitted by the operating system. it's possible you have another utility which is modifying your key events. What locale/keyboard type are you using?

**Comment by akitchen** [comment] 2023-10-19 21:50
no reply, can't reproduce, closing

**Closed by akitchen** 2023-10-19 21:50 UTC
